"""create legal_text_chunk table

Revision ID: 4286d94a6783
Revises: 
Create Date: 2025-10-04 00:10:13.893988

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4286d94a6783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # the vector type is not built-in, it’s defined by the pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_text_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('article_number', sa.Integer(), nullable=False),
    sa.Column('paragraph_number', sa.Integer(), nullable=True),
    sa.Column('chunk_type', sa.Enum('BODY', 'ELUCIDATION', name='chunk_type_enum'), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('doc_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_text_chunks')),
    sa.UniqueConstraint('source', 'article_number', 'paragraph_number', 'chunk_type', 'chunk_index', name=op.f('uq_legal_text_chunks_source'), postgresql_nulls_not_distinct=True),
    schema='public'
    )
    op.create_index(op.f('ix_legal_text_chunks_public_legal_text_chunks_embedding'), 'legal_text_chunks', ['embedding'], unique=False, schema='public', postgresql_using='hnsw', postgresql_with={'m': 12, 'ef_construction': 75}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_legal_text_chunks_public_legal_text_chunks_source'), 'legal_text_chunks', ['source', 'article_number', 'paragraph_number'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP EXTENSION IF EXISTS vector")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_text_chunks_public_legal_text_chunks_source'), table_name='legal_text_chunks', schema='public')
    op.drop_index(op.f('ix_legal_text_chunks_public_legal_text_chunks_embedding'), table_name='legal_text_chunks', schema='public', postgresql_using='hnsw', postgresql_with={'m': 12, 'ef_construction': 75}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('legal_text_chunks', schema='public')
    # ### end Alembic commands ###
