"""create legal_text_chunks table

Revision ID: d4d3dd86a68d
Revises: 
Create Date: 2025-09-24 22:20:52.481543

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d3dd86a68d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # the vector type is not built-in, it’s defined by the pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_text_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('paragraph', sa.String(), nullable=True),
    sa.Column('chunk_type', sa.Enum('BODY', 'ELUCIDATION', name='chunk_type_enum'), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('doc_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'article', 'paragraph', 'chunk_type', 'chunk_index'),
    schema='public'
    )
    op.create_index(op.f('ix_public_legal_text_chunks_id'), 'legal_text_chunks', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP EXTENSION IF EXISTS vector")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_legal_text_chunks_id'), table_name='legal_text_chunks', schema='public')
    op.drop_table('legal_text_chunks', schema='public')
    # ### end Alembic commands ###
